import type {
  Language,
  NavItem,
  QuickAction,
  RecentItem,
  AISuggestion,
  Statistic,
  PromptChip,
  Notification,
  Service,
  ServiceCategory,
  Complaint,
  Document,
  Scheme,
} from "@/types";

export const LANGUAGES: Language[] = [
  { code: "en", label: "English", nativeLabel: "English" },
  { code: "hi", label: "Hindi", nativeLabel: "हिन्दी" },
  { code: "ta", label: "Tamil", nativeLabel: "தமிழ்" },
  { code: "te", label: "Telugu", nativeLabel: "తెలుగు" },
  { code: "bn", label: "Bengali", nativeLabel: "বাংলা" },
  { code: "mr", label: "Marathi", nativeLabel: "मराठी" },
  { code: "gu", label: "Gujarati", nativeLabel: "ગુજરાતી" },
  { code: "kn", label: "Kannada", nativeLabel: "ಕನ್ನಡ" },
  { code: "ml", label: "Malayalam", nativeLabel: "മലയാളം" },
  { code: "pa", label: "Punjabi", nativeLabel: "ਪੰਜਾਬੀ" },
];

export const NAV_ITEMS: NavItem[] = [
  { id: "home", label: "Home", href: "/", icon: "Home" },
  { id: "ai-assistant", label: "AI Assistant", href: "/ai-assistant", icon: "Bot" },
  { id: "services", label: "Services", href: "/services", icon: "Building2" },
  { id: "complaints", label: "Complaints", href: "/complaints", icon: "AlertTriangle" },
  { id: "documents", label: "Documents", href: "/documents", icon: "FileText" },
  { id: "schemes", label: "Schemes", href: "/schemes", icon: "Gift" },
  { id: "resources", label: "Resources", href: "/resources", icon: "BookOpen" },
  { id: "profile", label: "Profile", href: "/profile", icon: "User" },
];

export const QUICK_ACTIONS: QuickAction[] = [
  {
    id: "ai-assistant",
    label: "AI Assistant",
    description: "Ask anything. Get instant answers & guidance.",
    icon: "Bot",
    href: "/ai-assistant",
    color: "#6B3FFF",
    bgColor: "#EDE9FE",
  },
  {
    id: "find-services",
    label: "Find Services",
    description: "Explore government services & how to apply.",
    icon: "Building2",
    href: "/services",
    color: "#10B981",
    bgColor: "#D1FAE5",
  },
  {
    id: "report-issue",
    label: "Report an Issue",
    description: "Report problems in your area in just a few steps.",
    icon: "AlertTriangle",
    href: "/complaints",
    color: "#F59E0B",
    bgColor: "#FEF3C7",
  },
  {
    id: "track-complaint",
    label: "Track Complaint",
    description: "Track real-time status of your complaints.",
    icon: "ClipboardList",
    href: "/complaints?tab=track",
    color: "#3B82F6",
    bgColor: "#DBEAFE",
  },
  {
    id: "schemes",
    label: "Schemes for You",
    description: "Discover schemes you may be eligible for.",
    icon: "Gift",
    href: "/schemes",
    color: "#EC4899",
    bgColor: "#FCE7F3",
  },
  {
    id: "language",
    label: "Language",
    description: "Change language & preferences.",
    icon: "Globe",
    href: "/settings/language",
    color: "#8B5CF6",
    bgColor: "#EDE9FE",
  },
];

export const RECENT_ITEMS: RecentItem[] = [
  {
    id: "1",
    title: "Driving License Renewal",
    subtitle: "Application in progress",
    status: "Documents Pending",
    statusColor: "orange",
    date: "20 May 2026",
    icon: "FileText",
    href: "/services?service=dl-renewal",
  },
  {
    id: "2",
    title: "Complaint #CMP-2026-1452",
    subtitle: "Street light not working",
    status: "Engineer Assigned",
    statusColor: "green",
    date: "19 May 2026",
    icon: "AlertTriangle",
    href: "/complaints?tab=track&id=CMP-2026-1452",
  },
  {
    id: "3",
    title: "PM Kisan Yojana",
    subtitle: "Check your eligibility",
    status: "Eligible",
    statusColor: "green",
    date: "18 May 2026",
    icon: "Gift",
    href: "/schemes?scheme=pm-kisan",
  },
];

export const AI_SUGGESTIONS: AISuggestion[] = [
  {
    id: "1",
    title: "You may be eligible for PM Kisan Yojana",
    description: "Check your eligibility and apply",
    icon: "Leaf",
    iconBg: "#D1FAE5",
    href: "/schemes?scheme=pm-kisan",
  },
  {
    id: "2",
    title: "Renew your vehicle insurance",
    description: "Your policy expires in 15 days",
    icon: "Shield",
    iconBg: "#DBEAFE",
    href: "/ai-assistant?q=How do I renew my vehicle insurance%3F",
  },
  {
    id: "3",
    title: "Apply for Birth Certificate",
    description: "Get your birth certificate online",
    icon: "FileText",
    iconBg: "#D1FAE5",
    href: "/ai-assistant?q=How do I apply for a birth certificate%3F",
  },
  {
    id: "4",
    title: "Register for Udyam (MSME)",
    description: "Register your business in a few simple steps",
    icon: "Building2",
    iconBg: "#FEF3C7",
    href: "/ai-assistant?q=How do I register for Udyam (MSME)%3F",
  },
];

export const STATISTICS: Statistic[] = [
  {
    id: "1",
    value: "12.4L+",
    label: "Services Delivered",
    icon: "Zap",
    iconBg: "#6B3FFF",
  },
  {
    id: "2",
    value: "5.8L+",
    label: "Issues Resolved",
    icon: "Users",
    iconBg: "#8B5CF6",
  },
  {
    id: "3",
    value: "98.7%",
    label: "Satisfaction Rate",
    icon: "Sun",
    iconBg: "#F59E0B",
  },
  {
    id: "4",
    value: "22+",
    label: "Languages Supported",
    icon: "Globe",
    iconBg: "#6B3FFF",
  },
];

export const PROMPT_CHIPS: PromptChip[] = [
  { id: "1", label: "Driving License" },
  { id: "2", label: "Pothole near me" },
  { id: "3", label: "Scholarship for students" },
  { id: "4", label: "Birth Certificate" },
  { id: "5", label: "Start a business" },
];

export const NOTIFICATIONS: Notification[] = [
  {
    id: "1",
    title: "Documents Pending",
    body: "Upload your Aadhaar card for Driving License Renewal",
    time: "2 hours ago",
    read: false,
  },
  {
    id: "2",
    title: "Complaint Updated",
    body: "Engineer has been assigned to your street light complaint",
    time: "5 hours ago",
    read: false,
  },
  {
    id: "3",
    title: "New Scheme Available",
    body: "You may be eligible for PM Awas Yojana. Check now.",
    time: "1 day ago",
    read: true,
  },
];

export const USER_PROFILE = {
  name: "Mithra",
  fullName: "Mithra Sharma",
  email: "mithra.sharma@example.com",
  avatar: null,
  location: "New Delhi, India",
};

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  { id: "all", label: "All Services", icon: "LayoutGrid" },
  { id: "identity", label: "Identity", icon: "User" },
  { id: "transport", label: "Transport", icon: "Car" },
  { id: "land", label: "Land & Property", icon: "Home" },
  { id: "education", label: "Education", icon: "BookOpen" },
  { id: "health", label: "Health", icon: "Heart" },
  { id: "business", label: "Business", icon: "Briefcase" },
  { id: "social", label: "Social Welfare", icon: "Users" },
];

export const SERVICES: Service[] = [
  {
    id: "driving-license",
    title: "Driving License",
    description: "Apply, renew, or update your driving license online without visiting the RTO.",
    category: "transport",
    department: "Ministry of Road Transport",
    estimatedTime: "15–30 days",
    documentsNeeded: ["Aadhaar Card", "Passport Photo", "Address Proof", "Medical Certificate"],
    icon: "Car",
    iconBg: "#DBEAFE",
    iconColor: "#3B82F6",
    isPopular: true,
    href: "/services",
  },
  {
    id: "passport",
    title: "Passport Services",
    description: "Apply for a new passport, renew existing, or get emergency travel documents.",
    category: "identity",
    department: "Ministry of External Affairs",
    estimatedTime: "7–45 days",
    documentsNeeded: ["Birth Certificate", "Aadhaar Card", "Address Proof", "Passport Photos"],
    icon: "BookOpen",
    iconBg: "#D1FAE5",
    iconColor: "#10B981",
    isPopular: true,
    href: "/services",
  },
  {
    id: "birth-certificate",
    title: "Birth Certificate",
    description: "Register a birth or obtain a birth certificate from the municipal corporation.",
    category: "identity",
    department: "Municipal Corporation",
    estimatedTime: "3–7 days",
    documentsNeeded: ["Hospital Discharge Summary", "Parents' Aadhaar", "Marriage Certificate"],
    icon: "FileText",
    iconBg: "#EDE9FE",
    iconColor: "#6B3FFF",
    isPopular: true,
    href: "/services",
  },
  {
    id: "ration-card",
    title: "Ration Card",
    description: "Apply for a new ration card or update existing details for your household.",
    category: "social",
    department: "Department of Food & Civil Supplies",
    estimatedTime: "14–30 days",
    documentsNeeded: ["Aadhaar Card", "Address Proof", "Income Certificate", "Family Photo"],
    icon: "Users",
    iconBg: "#FEF3C7",
    iconColor: "#F59E0B",
    href: "/services",
  },
  {
    id: "vehicle-registration",
    title: "Vehicle Registration",
    description: "Register your new vehicle or transfer ownership of an existing vehicle.",
    category: "transport",
    department: "Ministry of Road Transport",
    estimatedTime: "7–14 days",
    documentsNeeded: ["Invoice/Form 21", "Insurance Certificate", "PUC Certificate", "Aadhaar"],
    icon: "Car",
    iconBg: "#DBEAFE",
    iconColor: "#3B82F6",
    href: "/services",
  },
  {
    id: "income-certificate",
    title: "Income Certificate",
    description: "Get an income certificate for scholarships, government schemes, and subsidies.",
    category: "social",
    department: "Revenue Department",
    estimatedTime: "7–14 days",
    documentsNeeded: ["Aadhaar Card", "Salary Slips / IT Returns", "Address Proof"],
    icon: "FileText",
    iconBg: "#D1FAE5",
    iconColor: "#10B981",
    href: "/services",
  },
  {
    id: "udyam-registration",
    title: "Udyam Registration (MSME)",
    description: "Register your micro, small, or medium enterprise under the MSME Act.",
    category: "business",
    department: "Ministry of MSME",
    estimatedTime: "1–3 days",
    documentsNeeded: ["Aadhaar Card", "PAN Card", "Bank Account Details", "Business Address Proof"],
    icon: "Briefcase",
    iconBg: "#FCE7F3",
    iconColor: "#EC4899",
    isPopular: true,
    href: "/services",
  },
  {
    id: "scholarship",
    title: "Scholarship Portal",
    description: "Apply for central and state government scholarships for students of all levels.",
    category: "education",
    department: "Ministry of Education",
    estimatedTime: "30–60 days",
    documentsNeeded: ["Aadhaar Card", "Marksheets", "Bank Account", "Caste/Income Certificate"],
    icon: "BookOpen",
    iconBg: "#EDE9FE",
    iconColor: "#8B5CF6",
    href: "/services",
  },
  {
    id: "health-id",
    title: "Ayushman Bharat Health ID",
    description: "Create your ABHA (Ayushman Bharat Health Account) for digital health records.",
    category: "health",
    department: "National Health Authority",
    estimatedTime: "Instant",
    documentsNeeded: ["Aadhaar Card", "Mobile Number"],
    icon: "Heart",
    iconBg: "#FEE2E2",
    iconColor: "#EF4444",
    href: "/services",
  },
  {
    id: "land-records",
    title: "Land Records (Bhulekh)",
    description: "View and download your land records, khata, and property documents online.",
    category: "land",
    department: "Revenue Department",
    estimatedTime: "Instant",
    documentsNeeded: ["Survey Number", "Khasra Number"],
    icon: "Home",
    iconBg: "#FEF3C7",
    iconColor: "#F59E0B",
    href: "/services",
  },
  {
    id: "domicile-certificate",
    title: "Domicile Certificate",
    description: "Apply for a domicile or residence certificate for state-based reservations.",
    category: "identity",
    department: "Revenue Department",
    estimatedTime: "14–21 days",
    documentsNeeded: ["Aadhaar Card", "Voter ID", "School Leaving Certificate", "Address Proof"],
    icon: "MapPin",
    iconBg: "#D1FAE5",
    iconColor: "#10B981",
    href: "/services",
  },
  {
    id: "caste-certificate",
    title: "Caste Certificate",
    description: "Obtain SC/ST/OBC caste certificate for reservations and government benefits.",
    category: "social",
    department: "Revenue Department",
    estimatedTime: "14–30 days",
    documentsNeeded: ["Aadhaar Card", "Address Proof", "Self-Declaration", "Village Records"],
    icon: "FileText",
    iconBg: "#EDE9FE",
    iconColor: "#6B3FFF",
    href: "/services",
  },
];

export const COMPLAINTS: Complaint[] = [
  {
    id: "1",
    ticketId: "CMP-2026-1452",
    title: "Street light not working",
    description: "The street light near Sector 12 main road has been non-functional for 3 weeks causing safety hazard at night.",
    category: "Street Lighting",
    location: "Sector 12, Main Road, New Delhi - 110001",
    status: "assigned",
    priority: "high",
    createdAt: "2026-05-19",
    updatedAt: "2026-05-20",
    assignedTo: "Electrical Dept. – Er. Ramesh Kumar",
    timeline: [
      { id: "t1", label: "Complaint Submitted", description: "Your complaint has been registered successfully.", timestamp: "19 May 2026, 10:30 AM", status: "submitted" },
      { id: "t2", label: "Under Review", description: "Your complaint is being reviewed by the concerned department.", timestamp: "19 May 2026, 2:00 PM", status: "under_review" },
      { id: "t3", label: "Engineer Assigned", description: "Er. Ramesh Kumar has been assigned to resolve the issue.", timestamp: "20 May 2026, 9:00 AM", status: "assigned" },
    ],
  },
  {
    id: "2",
    ticketId: "CMP-2026-1380",
    title: "Pothole on main road",
    description: "Large pothole near the bus stop at MG Road causing accidents and traffic issues.",
    category: "Roads & Infrastructure",
    location: "MG Road, near Bus Stop, Bangalore - 560001",
    status: "in_progress",
    priority: "medium",
    createdAt: "2026-05-14",
    updatedAt: "2026-05-18",
    assignedTo: "PWD Team – Supervisor Mohan Singh",
    timeline: [
      { id: "t1", label: "Complaint Submitted", description: "Your complaint has been registered.", timestamp: "14 May 2026, 11:00 AM", status: "submitted" },
      { id: "t2", label: "Under Review", description: "Being reviewed by PWD.", timestamp: "15 May 2026, 10:00 AM", status: "under_review" },
      { id: "t3", label: "Team Assigned", description: "PWD repair team has been assigned.", timestamp: "17 May 2026, 8:30 AM", status: "assigned" },
      { id: "t4", label: "Work In Progress", description: "Repair work has started at the site.", timestamp: "18 May 2026, 9:00 AM", status: "in_progress" },
    ],
  },
  {
    id: "3",
    ticketId: "CMP-2026-1290",
    title: "Water supply disruption",
    description: "No water supply in our block for 5 days. Multiple residents are facing acute water shortage.",
    category: "Water Supply",
    location: "Block C, Vasant Kunj, New Delhi - 110070",
    status: "resolved",
    priority: "high",
    createdAt: "2026-05-08",
    updatedAt: "2026-05-12",
    assignedTo: "Delhi Jal Board",
    timeline: [
      { id: "t1", label: "Complaint Submitted", description: "Registered with Delhi Jal Board.", timestamp: "8 May 2026, 8:00 AM", status: "submitted" },
      { id: "t2", label: "Under Review", description: "Jal Board team reviewing pipeline.", timestamp: "8 May 2026, 3:00 PM", status: "under_review" },
      { id: "t3", label: "Team Assigned", description: "Plumber team assigned.", timestamp: "9 May 2026, 7:00 AM", status: "assigned" },
      { id: "t4", label: "Work In Progress", description: "Pipeline repair underway.", timestamp: "10 May 2026, 10:00 AM", status: "in_progress" },
      { id: "t5", label: "Resolved", description: "Water supply restored. Issue fixed.", timestamp: "12 May 2026, 6:00 PM", status: "resolved" },
    ],
  },
];

export const COMPLAINT_CATEGORIES = [
  "Street Lighting",
  "Roads & Infrastructure",
  "Water Supply",
  "Sanitation & Drainage",
  "Garbage Collection",
  "Public Transport",
  "Electricity",
  "Parks & Recreation",
  "Noise Pollution",
  "Other",
];

export const DOCUMENTS: Document[] = [
  {
    id: "1",
    name: "Aadhaar Card",
    type: "PDF",
    category: "Identity",
    size: "245 KB",
    uploadedAt: "12 Jan 2026",
    status: "verified",
    icon: "CreditCard",
    iconBg: "#EDE9FE",
    iconColor: "#6B3FFF",
  },
  {
    id: "2",
    name: "PAN Card",
    type: "PDF",
    category: "Identity",
    size: "180 KB",
    uploadedAt: "12 Jan 2026",
    status: "verified",
    icon: "CreditCard",
    iconBg: "#D1FAE5",
    iconColor: "#10B981",
  },
  {
    id: "3",
    name: "Driving License",
    type: "PDF",
    category: "Transport",
    size: "312 KB",
    uploadedAt: "5 Mar 2026",
    status: "pending",
    icon: "Car",
    iconBg: "#DBEAFE",
    iconColor: "#3B82F6",
  },
  {
    id: "4",
    name: "Birth Certificate",
    type: "PDF",
    category: "Identity",
    size: "198 KB",
    uploadedAt: "20 Feb 2026",
    status: "verified",
    icon: "FileText",
    iconBg: "#FEF3C7",
    iconColor: "#F59E0B",
  },
  {
    id: "5",
    name: "Income Certificate",
    type: "PDF",
    category: "Financial",
    size: "156 KB",
    uploadedAt: "1 Apr 2026",
    status: "verified",
    icon: "FileText",
    iconBg: "#FCE7F3",
    iconColor: "#EC4899",
  },
  {
    id: "6",
    name: "Vehicle Insurance",
    type: "PDF",
    category: "Transport",
    size: "420 KB",
    uploadedAt: "15 Jan 2026",
    status: "expired",
    icon: "Shield",
    iconBg: "#FEE2E2",
    iconColor: "#EF4444",
  },
];

export const SCHEMES: Scheme[] = [
  {
    id: "pm-kisan",
    title: "PM Kisan Samman Nidhi",
    description: "Direct income support of ₹6,000 per year to farmer families in three equal installments.",
    ministry: "Ministry of Agriculture",
    category: "Agriculture",
    eligibility: ["Small and marginal farmers", "Land holding up to 2 hectares", "Valid Aadhaar"],
    benefits: "₹6,000 per year in 3 installments of ₹2,000",
    icon: "Leaf",
    iconBg: "#D1FAE5",
    iconColor: "#10B981",
    isEligible: true,
    tag: "Eligible",
  },
  {
    id: "ayushman-bharat",
    title: "Ayushman Bharat – PMJAY",
    description: "Health cover of ₹5 lakh per family per year for secondary and tertiary hospitalization.",
    ministry: "Ministry of Health",
    category: "Health",
    eligibility: ["BPL families", "SECC database listed", "No existing health cover"],
    benefits: "₹5 lakh health cover per family per year",
    icon: "Heart",
    iconBg: "#FEE2E2",
    iconColor: "#EF4444",
    isEligible: true,
    tag: "Eligible",
  },
  {
    id: "pm-awas",
    title: "PM Awas Yojana (Urban)",
    description: "Credit-linked subsidy scheme for housing loans to EWS/LIG/MIG categories.",
    ministry: "Ministry of Housing",
    category: "Housing",
    eligibility: ["EWS/LIG/MIG income groups", "No pucca house owned", "First-time home buyer"],
    benefits: "Interest subsidy of 3%–6.5% on home loans",
    deadline: "31 Dec 2026",
    icon: "Home",
    iconBg: "#FEF3C7",
    iconColor: "#F59E0B",
    isEligible: false,
    tag: "Check Eligibility",
  },
  {
    id: "startup-india",
    title: "Startup India Initiative",
    description: "Support for startups through tax exemptions, patent support, and funding access.",
    ministry: "DPIIT",
    category: "Business",
    eligibility: ["Entity registered in India", "Less than 10 years old", "Turnover < ₹100 Cr"],
    benefits: "Tax exemption, IPR support, govt. tenders access",
    icon: "Briefcase",
    iconBg: "#EDE9FE",
    iconColor: "#6B3FFF",
    isEligible: false,
    tag: "Apply Now",
  },
  {
    id: "sukanya-samridhi",
    title: "Sukanya Samriddhi Yojana",
    description: "Small savings scheme for the girl child offering high interest and tax benefits.",
    ministry: "Ministry of Finance",
    category: "Finance",
    eligibility: ["Girl child below 10 years", "Resident Indian", "Only 2 accounts per family"],
    benefits: "8.2% interest p.a., tax deduction under 80C",
    icon: "Gift",
    iconBg: "#FCE7F3",
    iconColor: "#EC4899",
    isEligible: true,
    tag: "Eligible",
  },
  {
    id: "pmegp",
    title: "PMEGP – Employment Generation",
    description: "Credit-linked subsidy for setting up micro enterprises in rural and urban areas.",
    ministry: "Ministry of MSME",
    category: "Business",
    eligibility: ["Age 18+ years", "Min 8th grade education", "New enterprise only"],
    benefits: "15%–35% subsidy on project cost",
    icon: "Users",
    iconBg: "#DBEAFE",
    iconColor: "#3B82F6",
    isEligible: false,
    tag: "Apply Now",
  },
];

/** Detailed document checklists per service (used by rule engine) */
export const SERVICE_DOCUMENT_CHECKLISTS: Record<string, { name: string; description: string; required: boolean }[]> = {
  "driving-license": [
    { name: "Original Driving License", description: "Your current DL to be renewed", required: true },
    { name: "Aadhaar Card", description: "Valid identity proof issued by UIDAI", required: true },
    { name: "Address Proof", description: "Utility bill, bank statement, or Aadhaar with current address", required: true },
    { name: "Passport-size Photograph", description: "Recent white-background photo (3.5 × 4.5 cm)", required: true },
    { name: "Medical Certificate (Form 1A)", description: "Required only if age is above 40 years", required: false },
  ],
  "passport": [
    { name: "Birth Certificate", description: "Municipal birth certificate or school leaving certificate as proof of birth date", required: true },
    { name: "Aadhaar Card", description: "For identity and address verification", required: true },
    { name: "Address Proof", description: "Utility bill, bank statement, or Voter ID", required: true },
    { name: "Passport Photos", description: "Two recent white-background photos (4.5 × 3.5 cm)", required: true },
    { name: "Existing Passport", description: "For renewal — old passport in original", required: false },
  ],
  "birth-certificate": [
    { name: "Hospital Discharge Summary", description: "Original hospital record of birth", required: true },
    { name: "Parents' Aadhaar Cards", description: "Both parents' Aadhaar for identity proof", required: true },
    { name: "Marriage Certificate", description: "Parents' marriage certificate", required: true },
    { name: "Application Form", description: "Municipal corporation birth registration form", required: true },
  ],
  "ration-card": [
    { name: "Aadhaar Card", description: "Aadhaar of all family members", required: true },
    { name: "Address Proof", description: "Utility bill or rent agreement", required: true },
    { name: "Income Certificate", description: "Proof of family annual income", required: true },
    { name: "Family Photograph", description: "Recent family photograph with all members", required: true },
  ],
  "udyam-registration": [
    { name: "Aadhaar Card", description: "Proprietor's Aadhaar — linked to mobile number", required: true },
    { name: "PAN Card", description: "Business or personal PAN for tax records", required: true },
    { name: "Bank Account Details", description: "Business bank account with IFSC code", required: true },
    { name: "Business Address Proof", description: "Rent agreement or utility bill of business premise", required: true },
  ],
};
